name: "Release to SDKMan"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
jobs:
  sdkman:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: v${{ github.event.inputs.version }}
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4
        with:
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      - name: "🏆 Grails SDK Minor Release"
        env:
          DEVELOCITY_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          DEVELOCITY_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
          GVM_SDKVENDOR_KEY: ${{ secrets.GVM_SDKVENDOR_KEY }}
          GVM_SDKVENDOR_TOKEN: ${{ secrets.GVM_SDKVENDOR_TOKEN }}
        run: ./gradlew sdkMinorRelease
      - name: "Set output"
        id: set_output
        run: |
          echo ::set-output name=release_version::$(cat $GITHUB_OUTPUT)
        env:
          GITHUB_OUTPUT: ${{ github.workspace }}/build/release_version
